services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://docker-mysqldb:3306/akamaiDb?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - docker-mysqldb

    volumes:
      - .m2:/root/.m2

  docker-mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: akamaiDb
#      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
networks:
  springapimysql-net: